# Site settings
title: Mark; My Words
email:
description: > # this means to ignore newlines until "baseurl:"
  Hi, I'm Mark. I'm a Ruby on Rails programmer. Here are some of my thoughts,
  my ideas, my observations, my words.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://markadrianagbuya.github.io" # the base hostname & protocol for your site
twitter_username: markagbuya
github_username:  markadrianagbuya

# Build settings
markdown: kramdown
